export enum BeltType {
    White = 1,
    White1Yellow = 2,
    White2Yellow = 3,
    WhiteYellow = 4,
    Yellow = 5,
    YellowOrange = 6,
    Orange = 7,
    OrangeGreen = 8,
    Green = 9,
    GreenBlue = 10,
    Blue = 11,
    BlueBrown = 12,
    Brown = 13,
    Black = 14,
}